#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check
api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api' # Optional
